function [M,C,G] = dinamica_3R_numerica(in1,in2,in3)
%dinamica_3R_numerica
%    [M,C,G] = dinamica_3R_numerica(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    06-Jul-2026 16:38:07

I1 = in3(:,10);
I2 = in3(:,11);
I3 = in3(:,12);
dq1 = in2(1,:);
dq2 = in2(2,:);
dq3 = in2(3,:);
g = in3(:,13);
l1 = in3(:,4);
l2 = in3(:,5);
lc1 = in3(:,7);
lc2 = in3(:,8);
lc3 = in3(:,9);
m1 = in3(:,1);
m2 = in3(:,2);
m3 = in3(:,3);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = sin(q2);
t6 = sin(q3);
t7 = q1+q2;
t8 = q2+q3;
t9 = l1.^2;
t10 = l2.^2;
t11 = lc2.^2;
t12 = lc3.^2;
t13 = dq1+dq2+dq3;
t14 = l1.*t2;
t15 = cos(t7);
t16 = cos(t8);
t17 = l2.*t6;
t18 = q3+t7;
t19 = sin(t8);
t21 = l2.*m3.*t5;
t22 = lc2.*m2.*t5;
t23 = m3.*t10;
t24 = m2.*t11;
t25 = m3.*t12;
t27 = l1.*l2.*m3.*t3;
t28 = l1.*lc2.*m2.*t3;
t29 = l2.*lc3.*m3.*t4;
t20 = cos(t18);
t26 = l2.*t15;
t30 = l1.*t19;
t31 = l1.*t21;
t32 = l1.*t22;
t33 = lc3.*m3.*t17;
t34 = t29.*2.0;
t36 = lc3.*m3.*t19;
t38 = l1.*lc3.*m3.*t16;
t42 = I3+t25+t29;
t35 = lc3.*t20;
t37 = dq3.*t33;
t39 = lc3.*m3.*t30;
t41 = t17+t30;
t44 = t21+t22+t36;
t45 = t38+t42;
t47 = I2+I3+t23+t24+t25+t27+t28+t34+t38;
M = reshape([I1+t27+t28+t38+t47+m2.*t9+m3.*t9+lc1.^2.*m1,t47,t45,t47,I2+I3+t23+t24+t25+t34,t42,t45,t42,I3+t25],[3,3]);
if nargout > 1
    t40 = -t37;
    t43 = t33+t39;
    t46 = t31+t32+t39;
    C = reshape([-dq3.*t43-dq2.*t46,t40+dq1.*t46,dq2.*t33+dq1.*t43,-dq1.*l1.*t44-dq2.*l1.*t44-dq3.*lc3.*m3.*t41,t40,t33.*(dq1+dq2),-lc3.*m3.*t13.*t41,-t13.*t33,0.0],[3,3]);
end
if nargout > 2
    G = [g.*m2.*(t14+lc2.*t15)+g.*m3.*(t14+t26+t35)+g.*lc1.*m1.*t2;g.*m3.*(t26+t35)+g.*lc2.*m2.*t15;g.*m3.*t35];
end
end
