function [J_SC,J_ZC,SC,ZC] = calc_com_jacobian(q1,q2,q3)
%CALC_COM_JACOBIAN
%    [J_SC,J_ZC,SC,ZC] = CALC_COM_JACOBIAN(Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    13-Jul-2026 12:00:43

t2 = -q2;
t3 = -q3;
t4 = q2+t3;
t6 = q1+q3+t2;
t5 = cos(t4);
t7 = sin(t4);
t8 = cos(t6);
t9 = sin(t6);
t10 = t5.*4.239473684210526e-1;
t11 = t7.*4.239473684210526e-1;
t13 = t8.*4.459398496240602e-1;
J_SC = [t13,-t10-t13];
if nargout > 1
    t14 = t9.*4.459398496240602e-1;
    t12 = -t11;
    J_ZC = [-t14,t12+t14];
end
if nargout > 2
    SC = t12+t14+sin(q3).*(3.0./1.9e+1);
end
if nargout > 3
    ZC = t10+t13+cos(q3).*(3.0./1.9e+1);
end
end
