function [M,C,CdQ,G,B] = calc_dynamics(in1,in2)
%CALC_DYNAMICS
%    [M,C,CdQ,G,B] = CALC_DYNAMICS(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    12-Jul-2026 17:25:53

dq1 = in2(1,:);
dq2 = in2(3,:);
q1 = in1(1,:);
q2 = in1(3,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
t6 = dq1.^2;
t7 = dq2.^2;
t8 = -q2;
t9 = q1+t8;
t12 = t2.*3.766185;
t13 = t3.*3.5804475;
t10 = cos(t9);
t11 = sin(t9);
t14 = t10.*1.2686625e+1;
M = reshape([1.330425e+1,t12,t14,t12,1.1854815,t13,t14,t13,1.250775e+1],[3,3]);
if nargout > 1
    C = reshape([0.0,dq1.*t4.*(-3.766185),dq1.*t11.*(-1.2686625e+1),0.0,0.0,0.0,dq2.*t11.*1.2686625e+1,dq2.*t5.*(-3.5804475),0.0],[3,3]);
end
if nargout > 2
    CdQ = [t7.*t11.*1.2686625e+1;t4.*t6.*(-3.766185)-t5.*t7.*3.5804475;t6.*t11.*(-1.2686625e+1)];
end
if nargout > 3
    G = [t4.*(-2.9091555e+2);0.0;t5.*(-2.76568425e+2)];
end
if nargout > 4
    B = reshape([1.0e+2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0e+1],[3,3]);
end
end
